
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 133
#define YY_END_OF_BUFFER 134
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[491] =
    {   0,
        0,    0,  134,  132,  131,  130,  117,  132,  132,  124,
      116,  132,  111,  112,  122,  120,  108,  119,  115,  123,
       72,   71,  109,  105,  125,  110,  126,  129,  121,   69,
       69,   69,   69,   69,   69,   69,   69,   69,  113,  114,
      127,  132,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,  106,  128,
      107,  118,  104,    0,   80,    0,    0,   90,  107,   99,
       91,    0,    0,   88,   96,   84,   97,   87,   98,    0,
       75,    0,    3,   89,   76,   72,    0,    0,   72,   72,
        0,   72,   71,   71,   71,   71,  114,  106,  113,   95,

      101,  103,  102,   94,   69,   69,   69,   69,   69,   69,
       69,   69,    0,    0,   69,   69,   69,   69,   92,    0,
        0,    0,    0,    0,    0,    0,    0,   69,   69,   69,
       69,   69,   69,   69,   13,   69,   69,   69,   69,   69,
       69,   69,   69,   22,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   93,
      100,   80,    0,    0,    0,    0,    0,   73,    0,    0,
       81,    0,   75,    0,    0,    0,    3,    0,   76,    0,
       74,   72,   72,   72,   72,    0,   70,   71,   71,   71,
       71,   83,   82,   69,   59,   69,   58,   60,   69,   66,

       61,   69,   69,   56,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   20,   69,   69,   69,
       24,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,    0,    0,    0,    0,    0,    0,   75,    0,    1,
        0,   76,   74,   72,    0,    0,   70,    0,   70,   70,
       71,   69,   54,   69,   69,   69,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    6,   45,   69,    8,    9,
       69,   69,   69,   69,   15,   16,   69,   69,   69,   69,

       69,   21,   69,   25,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   68,   69,   69,   69,
       39,   69,   69,    0,    0,    0,    0,    0,    1,    0,
        0,    0,    0,   70,   70,    0,   77,   70,   70,   69,
       53,   55,   69,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    7,   10,   69,   69,   69,   69,   67,   19,
       69,   69,   69,   69,   69,   69,   69,   69,   29,   69,
       69,   69,   69,   69,   69,   69,   37,   69,   69,   41,
        0,    2,    0,   78,    0,   79,   77,   70,   69,   69,
       69,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       69,   69,   14,   18,   69,   69,   23,   69,   69,   69,
       28,   69,   30,   17,   31,   32,   33,   35,   69,   69,
       69,    5,   78,   79,   69,   69,   69,    0,    0,   44,
        0,    0,    0,    0,    0,    0,    0,   69,   12,   62,
        4,   69,   69,   69,   65,   69,   36,   69,   69,   69,
       69,   69,   42,   43,   46,   47,    0,    0,    0,    0,
       52,   11,   63,   26,   27,   64,   69,   38,   40,   69,
       86,   85,    0,   49,    0,    0,   69,   57,   48,    0,
        0,   34,    0,    0,    0,    0,    0,   51,   50,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   31,   33,   34,
       35,   36,   37,   36,   36,   38,   39,   40,   36,   41,
       36,   42,   43,   44,   45,   36,   36,   46,   36,   36,
       47,   48,   49,   50,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   36,   61,   62,   63,   64,
       65,   66,   36,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,   77,   78,   79,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[80] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        7,    7,    1,    1,    1,    1,    1,    3,    1,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    1,    3,    1,    1,
        8,    6,    6,    7,    7,    7,    6,    8,    8,    8,
        8,    8,    8,    9,    8,    8,    9,    8,    9,    8,
        9,    8,    9,    8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[504] =
    {   0,
        0,    0,  825,  826,  826,  826,  798,   74,  768,   55,
       74,  774,  826,  826,  795,   70,  826,   71,   69,   81,
      106,   91,  793,  826,   93,  793,   66,  826,  826,    0,
      753,   51,   54,  753,  124,   52,  760,  759,  826,  826,
      788,  105,  743,   66,   98,   76,   96,  102,   90,  102,
      747,  759,  754,  114,   98,  171,  744,  749,  826,   94,
      826,  826,  826,  132,  185,  165,  751,  826,  826,  826,
      826,  165,  174,  826,  826,  826,  826,  826,  826,  789,
      177,  101,    0,  826,  184,  231,  239,  205,  162,   47,
      788,  150,  246,  204,  140,  192,  826,  826,  826,  778,

      826,  826,  826,  777,    0,  740,  760,  742,  754,  757,
      745,  792,  195,  747,  753,  733,  737,  722,  826,  147,
      725,  733,  725,  722,  717,  726,  727,  714,  717,  725,
      712,  727,  714,  720,  706,  707,  704,  704,  710,  706,
      703,  700,  699,    0,  167,  703,  699,  212,  711,  699,
      213,  223,  703,  692,  695,  754,  122,  223,  699,  826,
      826,  294,  752,  283,  225,    0,  700,  826,  293,    0,
      826,  301,  826,  279,  743,  296,    0,  314,  826,  305,
      323,  241,  826,  717,  692,    0,  321,  249,  826,  715,
      690,  826,  826,  689,    0,  694,    0,    0,  683,  826,

        0,  684,  677,    0,  686,  680,  681,  679,  690,  674,
      688,  672,  668,  672,  674,  683,  678,  666,  237,  680,
      678,  674,  666,  672,  659,  674,  669,  680,  658,  662,
        0,  663,  668,  659,  649,  647,  647,  648,  650,  655,
      656,  642,  640,  640,  652,  651,  641,  645,  649,  651,
      640,  331,  386,  641,  336,  434,  348,  352,  334,  687,
      356,  438,  826,  826,  288,  299,  343,  379,  269,  359,
      826,  643,    0,  639,  628,  623,  637,  631,  627,  636,
      633,  634,  620,  632,  623,    0,    0,  625,    0,    0,
      616,  624,  613,  620,    0,    0,  614,  624,  610,  626,

      603,    0,  612,    0,  613,  606,  606,  605,  611,  601,
      613,  606,  602,  606,  611,  610,    0,  608,  598,  603,
        0,  591,  603,  312,    0,  594,  300,    0,  826,  644,
      340,  411,  459,  352,  826,  426,  477,  618,  593,  600,
        0,    0,  372,  589,  592,  589,  583,  589,  579,  587,
      587,  558,    0,    0,  536,  537,  541,  529,    0,    0,
      538,  524,  522,  514,  498,  504,  499,  497,    0,  506,
      503,  501,  503,  487,  496,  498,    0,  489,  492,    0,
      495,  537,  430,  483,  487,  503,  826,  826,  480,  478,
      477,  337,  492,  488,  483,  478,  468,  482,  480,  482,

      462,  462,    0,    0,  471,  473,    0,  472,  471,  472,
        0,  456,    0,    0,    0,    0,  468,    0,  461,  460,
      452,  826,  826,  826,  453,  450,  447,  433,  437,  826,
      420,  438,  433,  417,  432,  426,  423,  415,    0,    0,
        0,  408,  402,  394,  394,  394,    0,  382,  380,  370,
      402,  400,  826,  826,  826,  826,  357,  359,  360,  348,
      826,    0,    0,    0,    0,    0,  347,    0,    0,  332,
      826,  826,  320,  826,  314,  298,  295,    0,  826,  210,
      203,    0,  172,  162,  141,   81,   46,  826,  826,  826,
      565,  574,  578,  585,  592,  601,  610,  615,  617,  619,

      626,  630,  637
    } ;

static const flex_int16_t yy_def[504] =
    {   0,
      490,    1,  490,  490,  490,  490,  490,  491,  490,  490,
      490,  492,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  490,  490,
      490,  490,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  490,  490,
      490,  490,  490,  491,  490,  494,  490,  490,  490,  490,
      490,  492,  495,  490,  490,  490,  490,  490,  490,  490,
      490,  496,  497,  490,  490,  490,  490,  490,  490,  490,
      498,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  493,  493,  493,  493,  493,  493,
      493,  493,  491,  492,  493,  493,  493,  493,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  490,
      490,  490,  490,  490,  491,  499,  490,  490,  492,  500,
      490,  490,  490,  496,  501,  496,  497,  490,  490,  490,
      490,  490,  490,  490,  490,  502,  498,  490,  490,  490,
      490,  490,  490,  493,  493,  493,  493,  493,  493,  490,

      493,  493,  493,  493,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  491,  491,  490,  492,  492,  490,  490,  501,  503,
      490,  490,  490,  490,  502,  502,  490,  490,  490,  490,
      490,  493,  493,  493,  493,  493,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  491,  253,  490,  492,  256,  490,  503,
      503,  490,  490,  490,  490,  490,  490,  490,  490,  493,
      493,  493,  493,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      490,  503,  490,  490,  490,  490,  490,  490,  493,  493,
      493,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  490,  490,  490,  493,  493,  493,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  493,  493,  493,
      493,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  493,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  493,  493,  493,  493,  493,  493,  493,  493,  493,
      490,  490,  490,  490,  490,  490,  493,  493,  490,  490,
      490,  493,  490,  490,  490,  490,  490,  490,  490,    0,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490
    } ;

static const flex_int16_t yy_nxt[906] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       30,   31,   32,   30,   33,   30,   34,   35,   30,   30,
       36,   37,   38,   30,   35,   30,   39,    4,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   30,   50,
       30,   51,   30,   30,   30,   52,   53,   54,   55,   56,
       57,   58,   30,   30,   30,   59,   60,   61,   62,   65,
       68,   69,   70,   75,  184,   80,   77,   81,   81,   81,
       81,  103,  104,   82,  109,   76,   78,   79,   83,   71,

       98,  107,  115,  175,  110,  108,   84,   85,  185,   93,
       93,   93,   93,  176,  489,   99,  116,  100,  101,  160,
      111,   66,   85,   88,   86,   86,   87,   87,   94,  113,
      129,  134,  130,  114,  120,   95,  121,   65,   88,  122,
      135,  123,  488,   89,  124,  142,   88,  125,  126,  131,
       90,   91,   96,  139,  143,  127,  132,  136,  144,  137,
       95,   88,  133,  140,  154,  145,  141,   92,  138,  149,
      161,  155,  150,  151,  168,   90,  113,  190,   91,   66,
      114,  247,  152,  165,  165,  153,  162,  162,  162,  248,
      113,  156,  169,  169,  183,   81,   81,   81,   81,  182,

       65,  191,   81,   81,   81,   81,  183,  487,  205,  172,
      173,  182,   73,  486,  173,  206,  178,  179,  180,  183,
      180,  179,  163,  181,  181,  181,  181,  485,  230,  163,
       65,  183,  172,  173,  157,  231,  189,  166,  173,  178,
      179,  188,   66,  252,  252,  179,  170,   85,  189,   86,
       86,   87,   87,  188,  164,   85,  484,   87,   87,   87,
       87,  189,   85,   88,   93,   93,   93,   93,   89,  234,
      239,   88,   66,  189,  242,   90,  240,  483,   88,  235,
      236,  175,  249,   94,  250,  183,   88,  241,  113,  243,
       95,  176,   92,  189,   88,  162,  162,  162,  175,  113,

       90,   88,  168,  163,  291,  292,  338,   96,  176,  168,
      183,  255,  255,  260,  257,   95,  257,   65,  189,  258,
      258,  258,  258,  181,  181,  181,  181,  261,  332,  261,
      339,  163,  262,  262,  262,  262,   65,  266,  163,  333,
       73,  181,  181,  181,  181,  168,  259,   73,  482,  324,
      324,  329,  331,  332,  327,  327,  263,  382,  267,   66,
      263,  268,  481,  164,  333,  269,  258,  258,  258,  258,
      258,  258,  258,  258,  262,  262,  262,  262,   66,  263,
      334,  480,  270,   73,  263,  173,  268,  335,  428,  173,
      269,   65,  336,  479,  336,  478,  335,  337,  337,  337,

      337,  429,  477,  335,  325,  325,  325,  325,  173,  476,
      390,  475,  335,  173,  391,  325,  325,  325,  325,  325,
      334,  335,  474,  473,  383,  472,  383,  471,  335,  384,
      384,  384,  384,   66,  470,  469,  468,  325,  325,  325,
      325,  325,  325,  168,  337,  337,  337,  337,  384,  384,
      384,  384,  328,  328,  328,  328,  262,  262,  262,  262,
      467,  466,  465,  328,  328,  328,  328,  328,  464,  463,
      462,  179,  385,  461,  385,  179,  460,  386,  386,  386,
      386,   73,  459,  458,  457,  328,  328,  328,  328,  328,
      328,  456,  455,  454,  179,  337,  337,  337,  337,  179,

      453,  384,  384,  384,  384,  386,  386,  386,  386,  452,
      387,  451,  450,  449,  387,  448,  423,  447,  446,  445,
      423,  386,  386,  386,  386,  444,  443,  442,  441,  440,
      439,  438,  437,  387,  436,  435,  424,  434,  387,  423,
      424,  433,  432,  431,  423,  430,  427,  426,  425,  331,
      422,  421,  420,  419,  418,  417,  416,  415,  414,  424,
      413,  412,  411,  410,  424,   64,  409,   64,   64,   64,
       64,   64,   64,   64,   72,  408,   72,  407,   72,   72,
       72,   72,   72,  105,  105,  105,  105,   64,   64,  406,
       64,  405,  404,   64,   72,   72,  403,   72,  402,  401,

       72,  174,  174,  174,  174,  174,  174,  174,  174,  174,
      177,  400,  177,  177,  177,  177,  177,  177,  177,  187,
      187,  187,  253,  253,  256,  256,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  265,  265,  330,  399,  330,
      330,  330,  330,  330,  330,  330,  398,  397,  396,  395,
      394,  393,  392,  389,  388,  388,  331,  381,  380,  379,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  367,  366,  365,  364,  363,  362,  361,  360,  359,
      358,  357,  356,  355,  354,  353,  352,  351,  350,  349,
      348,  347,  346,  345,  344,  343,  342,  341,  340,  331,

      326,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  271,  264,  264,  259,  254,  113,  251,  113,
      246,  245,  244,  238,  237,  233,  232,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      204,  203,  202,  201,   73,  200,  199,  198,  197,  196,

      195,  194,  193,  192,  186,  171,  167,  159,  158,  148,
      147,  146,  128,  119,  118,  117,  112,  106,  102,   97,
       74,   73,   67,   63,  490,    3,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490
    } ;

static const flex_int16_t yy_chk[906] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
       10,   10,   11,   16,   90,   19,   18,   19,   19,   19,
       19,   27,   27,   20,   33,   16,   18,   18,   20,   11,

       25,   32,   36,   82,   33,   32,   20,   22,   90,   22,
       22,   22,   22,   82,  487,   25,   36,   25,   25,   60,
       33,    8,   21,   22,   21,   21,   21,   21,   22,   35,
       44,   46,   44,   35,   42,   22,   42,   64,   21,   42,
       46,   42,  486,   21,   42,   49,   22,   42,   42,   45,
       21,   21,   22,   48,   49,   42,   45,   47,   50,   47,
       22,   21,   45,   48,   55,   50,   48,   21,   47,   54,
       60,   55,   54,   54,   72,   21,   56,   95,   21,   64,
       56,  157,   54,   66,   66,   54,   65,   65,   65,  157,
       65,   56,   73,   73,   92,   81,   81,   81,   81,   89,

      113,   95,   85,   85,   85,   85,   89,  485,  120,   81,
       81,   92,   72,  484,   81,  120,   85,   85,   88,   92,
       88,   85,   65,   88,   88,   88,   88,  483,  145,   65,
      165,   89,   81,   81,   56,  145,   96,   66,   81,   85,
       85,   94,  113,  165,  165,   85,   73,   86,   94,   86,
       86,   86,   86,   96,   65,   87,  481,   87,   87,   87,
       87,   96,   93,   86,   93,   93,   93,   93,   86,  148,
      151,   87,  165,   94,  152,   86,  151,  480,   93,  148,
      148,  174,  158,   93,  158,  182,   86,  151,  164,  152,
       93,  174,   86,  188,   87,  162,  162,  162,  176,  162,

       86,   93,  169,  164,  219,  219,  269,   93,  176,  327,
      182,  169,  169,  176,  172,   93,  172,  324,  188,  172,
      172,  172,  172,  180,  180,  180,  180,  178,  265,  178,
      269,  162,  178,  178,  178,  178,  252,  187,  162,  266,
      169,  181,  181,  181,  181,  255,  259,  327,  477,  252,
      252,  259,  331,  265,  255,  255,  181,  331,  187,  324,
      181,  187,  476,  162,  266,  187,  257,  257,  257,  257,
      258,  258,  258,  258,  261,  261,  261,  261,  252,  181,
      267,  475,  187,  255,  181,  258,  187,  267,  392,  258,
      187,  253,  268,  473,  268,  470,  334,  268,  268,  268,

      268,  392,  467,  270,  253,  253,  253,  253,  258,  460,
      343,  459,  267,  258,  343,  253,  253,  253,  253,  253,
      270,  334,  458,  457,  332,  452,  332,  451,  270,  332,
      332,  332,  332,  253,  450,  449,  448,  253,  253,  253,
      253,  253,  253,  256,  336,  336,  336,  336,  383,  383,
      383,  383,  256,  256,  256,  256,  262,  262,  262,  262,
      446,  445,  444,  256,  256,  256,  256,  256,  443,  442,
      438,  262,  333,  437,  333,  262,  436,  333,  333,  333,
      333,  256,  435,  434,  433,  256,  256,  256,  256,  256,
      256,  432,  431,  429,  262,  337,  337,  337,  337,  262,

      428,  384,  384,  384,  384,  385,  385,  385,  385,  427,
      337,  426,  425,  421,  337,  420,  384,  419,  417,  412,
      384,  386,  386,  386,  386,  410,  409,  408,  406,  405,
      402,  401,  400,  337,  399,  398,  386,  397,  337,  384,
      386,  396,  395,  394,  384,  393,  391,  390,  389,  382,
      381,  379,  378,  376,  375,  374,  373,  372,  371,  386,
      370,  368,  367,  366,  386,  491,  365,  491,  491,  491,
      491,  491,  491,  491,  492,  364,  492,  363,  492,  492,
      492,  492,  492,  493,  493,  493,  493,  494,  494,  362,
      494,  361,  358,  494,  495,  495,  357,  495,  356,  355,

      495,  496,  496,  496,  496,  496,  496,  496,  496,  496,
      497,  352,  497,  497,  497,  497,  497,  497,  497,  498,
      498,  498,  499,  499,  500,  500,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  502,  502,  503,  351,  503,
      503,  503,  503,  503,  503,  503,  350,  349,  348,  347,
      346,  345,  344,  340,  339,  338,  330,  326,  323,  322,
      320,  319,  318,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  303,  301,  300,  299,  298,
      297,  294,  293,  292,  291,  288,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  272,  260,

      254,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  203,  202,  199,  196,
      194,  191,  190,  185,  184,  175,  167,  163,  159,  156,
      155,  154,  153,  150,  149,  147,  146,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      118,  117,  116,  115,  114,  112,  111,  110,  109,  108,

      107,  106,  104,  100,   91,   80,   67,   58,   57,   53,
       52,   51,   43,   41,   38,   37,   34,   31,   26,   23,
       15,   12,    9,    7,    3,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,

      490,  490,  490,  490,  490
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 25 "lex.l"
#include <stdio.h>
#include "y.tab.h"
  class tree_typedecl; 
//#include "symtabold.h"
//#include "../include/tree.h"
// "#define"{WS}*{ALPHANUM}                               { yylval.text=malloc(sizeof(yytext));strcpy(yylval.text,yytext);printf("macro stmt %s\n",yylval.text);return STRING_LITERAL; }

extern void yyerror(const char *);  /* prints grammar violation message */

extern int sym_type(const char *);  /* returns type from symbol table */
int COMP_FLAG=0,DECL_FLAG=0,br_cnt=0;
//extern class globsymtable *currsymtab;
extern int LINENO,macroflag;
int sym_type(char *identifier){
//printf("***************SYM_TYPE****************************%s\n",identifier);
//tree_typedecl *x=currsymtab->sym->findtypedefsymbol(identifier);
//if(x!=NULL){
//printf("\n TYPEDEFED DATA TYPE\n");
//if(x->tpdef==1) {
//yylval.text=x->vname;
//return TYPEDEF_NAME;

//}

//yylval.text=x->vname;
//printf("returning identifier\n");
//return IDENTIFIER;
//}
//printf("returning identifier\n");
return IDENTIFIER;
}

static void comment(void);
static void hash_define();
static int check_type(void);
#line 844 "lex.yy.c"
#line 845 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "lex.l"

#line 1064 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 491 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 826 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 63 "lex.l"
{/*multiline comment*/}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "lex.l"
{ /* comment();*/ printf("COMMENT %s ",yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "lex.l"
{ /* consume //-comment */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "lex.l"
{return GETTYPE;}    
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "lex.l"
{printf("HASHDEFINE\n");macroflag=0;return HASH_DEFINE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "lex.l"
{ return(AUTO); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "lex.l"
{ return(BREAK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "lex.l"
{ return(CASE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "lex.l"
{ return(CHAR); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "lex.l"
{ return(CONST); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "lex.l"
{ return(CONTINUE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "lex.l"
{ return(DEFAULT); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "lex.l"
{ return(DO); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "lex.l"
{ return(DOUBLE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "lex.l"
{ return(ELSE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "lex.l"
{ return(ENUM); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "lex.l"
{ return (SINGLE);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "lex.l"
{ return(EXTERN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "lex.l"
{ return(FLOAT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "lex.l"
{ return(FOR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "lex.l"
{ return(GOTO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "lex.l"
{ return(IF); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "lex.l"
{ return(INLINE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "lex.l"
{ return(INT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "lex.l"
{ return(LONG); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "lex.l"
{ return(REGISTER); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "lex.l"
{ return(RESTRICT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "lex.l"
{ return(RETURN); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "lex.l"
{ return(SHORT); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "lex.l"
{ return(SIGNED); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "lex.l"
{ return(SIZEOF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "lex.l"
{ return(STATIC); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "lex.l"
{  return(STRUCT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "lex.l"
{  return(STRUCT_REC); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "lex.l"
{ return(SWITCH); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "lex.l"
{ return(TYPEDEF); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "lex.l"
{ return(UNION); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "lex.l"
{ return(UNSIGNED); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "lex.l"
{ return(VOID); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "lex.l"
{ return(VOLATILE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "lex.l"
{ return(WHILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "lex.l"
{ return ALIGNAS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "lex.l"
{ return ALIGNOF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "lex.l"
{ return ATOMIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "lex.l"
{ return BOOL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "lex.l"
{ return COMPLEX; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "lex.l"
{ return GENERIC; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "lex.l"
{ return IMAGINARY; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "lex.l"
{ return NORETURN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "lex.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "lex.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "lex.l"
{ return FUNC_NAME; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "lex.l"
{return GRAPH;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "lex.l"
{return EDGE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "lex.l"
{return POINT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "lex.l"
{return SET;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "lex.l"
{return COLLECTION;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "lex.l"
{ return GPU;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "lex.l"
{return E_P;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "lex.l"
{return G_P;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "lex.l"
{return P_P;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "lex.l"
{return FOREACH;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 125 "lex.l"
{return PARALLEL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 126 "lex.l"
{return SECTIONS;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 127 "lex.l"
{return SECTION;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 128 "lex.l"
{/*yylval.text=malloc(sizeof(yytext));strcpy(yylval.text,yytext);*/return INOLD;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 129 "lex.l"
{ yylval.ival=0; return B_CONSTANT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 130 "lex.l"
{ yylval.ival=1; return B_CONSTANT;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 133 "lex.l"
{ yylval.text=malloc(sizeof(yytext));strcpy(yylval.text,yytext);return check_type(); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 135 "lex.l"
{ yylval.ival=atoi(yytext);return I_CONSTANT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 136 "lex.l"
{ yylval.ival=atoi(yytext);return I_CONSTANT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 137 "lex.l"
{ yylval.ival=atoi(yytext);return I_CONSTANT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 138 "lex.l"
{ 
yylval.text=calloc(sizeof(yytext)+50,sizeof(char));for(int i=0;i<sizeof(yytext)+50;i++)yylval.text[i]='\0';
strcpy(yylval.text,yytext);return STRING_LITERAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 141 "lex.l"
{ yylval.fval=atof(yytext);return F_CONSTANT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 142 "lex.l"
{ yylval.fval=atof(yytext);return F_CONSTANT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 143 "lex.l"
{ yylval.fval=atof(yytext);return F_CONSTANT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "lex.l"
{ yylval.fval=atof(yytext);return F_CONSTANT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "lex.l"
{ yylval.fval=atof(yytext);return F_CONSTANT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "lex.l"
{ yylval.fval=atof(yytext);return F_CONSTANT; }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 148 "lex.l"
{ yylval.text=calloc(sizeof(yytext)+100,sizeof(char));strcpy(yylval.text,yytext);return STRING_LITERAL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 150 "lex.l"
{ return ELLIPSIS; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 151 "lex.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 152 "lex.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 153 "lex.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 154 "lex.l"
{ return RADD_ASSIGN; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 155 "lex.l"
{ return RMUL_ASSIGN; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 156 "lex.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 157 "lex.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 158 "lex.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 159 "lex.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 160 "lex.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 161 "lex.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 162 "lex.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 163 "lex.l"
{ return RIGHT_OP; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 164 "lex.l"
{ return LEFT_OP; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 165 "lex.l"
{ return INC_OP; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 166 "lex.l"
{ return DEC_OP; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 167 "lex.l"
{ return PTR_OP; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 168 "lex.l"
{ return AND_OP; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 169 "lex.l"
{ return OR_OP; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 170 "lex.l"
{ return LE_OP; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 171 "lex.l"
{ return GE_OP; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 172 "lex.l"
{ return EQ_OP; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 173 "lex.l"
{ return NE_OP; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 174 "lex.l"
{ return ';'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 175 "lex.l"
{ return '{'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 176 "lex.l"
{ return '}'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 177 "lex.l"
{ return ','; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 178 "lex.l"
{ return ':'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 179 "lex.l"
{ return '='; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 180 "lex.l"
{ br_cnt++;return '('; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 181 "lex.l"
{ br_cnt--;return ')'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 182 "lex.l"
{ return '['; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 183 "lex.l"
{ return ']'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 184 "lex.l"
{ return '.'; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 185 "lex.l"
{ return '&'; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 186 "lex.l"
{ return '!'; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 187 "lex.l"
{ return '~'; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 188 "lex.l"
{ return '-'; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 189 "lex.l"
{ return '+'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 190 "lex.l"
{ return '@'; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 191 "lex.l"
{ return '*'; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 192 "lex.l"
{ return '/'; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 193 "lex.l"
{ return '%'; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 194 "lex.l"
{ return '<'; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 195 "lex.l"
{ return '>'; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 196 "lex.l"
{ return '^'; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 197 "lex.l"
{ return '|'; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 198 "lex.l"
{ return '?'; }
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 199 "lex.l"
{LINENO++;}
	YY_BREAK
case 131:
/* rule 131 can match eol */
YY_RULE_SETUP
#line 200 "lex.l"
{ if((macroflag==0)||(macroflag==1 &&br_cnt==0)) {macroflag++; return WHITE_SPACE;}/* whitespace separates tokens */ }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 201 "lex.l"
{ /* discard bad characters */ }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 203 "lex.l"
ECHO;
	YY_BREAK
#line 1792 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 491 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 491 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 490);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 203 "lex.l"


int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}
void skipline(){
int c;

    while ((c = getchar()) != '\n');
}
static void hash_define(){
char def[1000];
int i=1,c;
def[0]='#';
printf("HASH DEFINE\n");
while((c=getchar())!='\n')def[i++]=c;
def[i]='\n';
yylval.text=malloc(sizeof(char)*(i+1));
strncpy(yylval.text,def,i);
(yylval.text)[i+1]='\0';
return STRING_LITERAL;
}

static void comment(void)
{
    int c;
    while (scanf("%c",&c) != 0){
        if (c == '*')
        {
            while ((scanf("%c",&c)) == '*')
                ;

            if (c == '/')
                return;
}
            if (c == 0)
                break;
printf("%c",c);
        }
    yyerror("unterminated comment");
}

static int check_type(void)
{
    switch (sym_type(yytext))
    {
    case TYPEDEF_NAME: {printf("here\n");               /* previously defined */
        return TYPEDEF_NAME;break;
               }
    case ENUMERATION_CONSTANT: {
       /* previously defined */
        return ENUMERATION_CONSTANT;

}
    default:                          /* includes undefined */
        return IDENTIFIER;
    }
}

/*"Points"                                  {return POINTS;}
"Edges"                                  {return EDGES;}
"Nbrs"                                   {return NBRS;}
"InNbrs"                                 {return INNBRS;}
"OutNbrs"                                 {return OUTNBRS;}
"Items"                                  {return ITEMS;}*/

